// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgS7hHESEt6wGwpN4T-43xSWa-lOk18lU',
    appId: '1:43847641418:web:c12875378208ef6a0a39b3',
    messagingSenderId: '43847641418',
    projectId: 'medicbook-7c081',
    authDomain: 'medicbook-7c081.firebaseapp.com',
    storageBucket: 'medicbook-7c081.firebasestorage.app',
    measurementId: 'G-LK4ZCVKHH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa0cFtYDFq2UG5goq6H3XHyppHSUnl0tg',
    appId: '1:43847641418:android:0a26a766cede439d0a39b3',
    messagingSenderId: '43847641418',
    projectId: 'medicbook-7c081',
    storageBucket: 'medicbook-7c081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2rOCcthIEq6ETEDKshjBwojxec24pGU',
    appId: '1:43847641418:ios:418b3c33d1676da40a39b3',
    messagingSenderId: '43847641418',
    projectId: 'medicbook-7c081',
    storageBucket: 'medicbook-7c081.firebasestorage.app',
    iosBundleId: 'com.example.medibook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl2rOCcthIEq6ETEDKshjBwojxec24pGU',
    appId: '1:43847641418:ios:418b3c33d1676da40a39b3',
    messagingSenderId: '43847641418',
    projectId: 'medicbook-7c081',
    storageBucket: 'medicbook-7c081.firebasestorage.app',
    iosBundleId: 'com.example.medibook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgS7hHESEt6wGwpN4T-43xSWa-lOk18lU',
    appId: '1:43847641418:web:eca06b4fda1032f70a39b3',
    messagingSenderId: '43847641418',
    projectId: 'medicbook-7c081',
    authDomain: 'medicbook-7c081.firebaseapp.com',
    storageBucket: 'medicbook-7c081.firebasestorage.app',
    measurementId: 'G-RBP4WP8B9V',
  );
}
